<a href="https://colab.research.google.com/github/AbinReji07/water_portability/blob/main/water_portability_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df=pd.read_csv("/content/water_potability.csv")
df

ph    Hardness       Solids  Chloramines     Sulfate  \
0          NaN  204.890456  20791.31898     7.300212  368.516441   
1     3.716080  129.422921  18630.05786     6.635246         NaN   
2     8.099124  224.236259  19909.54173     9.275884         NaN   
3     8.316766  214.373394  22018.41744     8.059332  356.886136   
4     9.092223  181.101509  17978.98634     6.546600  310.135738   
...        ...         ...          ...          ...         ...   
3271  4.668102  193.681736  47580.99160     7.166639  359.948574   
3272  7.808856  193.553212  17329.80216     8.061362         NaN   
3273  9.419510  175.762646  33155.57822     7.350233         NaN   
3274  5.126763  230.603758  11983.86938     6.303357         NaN   
3275  7.874671  195.102299  17404.17706     7.509306         NaN   

      Conductivity  Organic_carbon  Trihalomethanes  Turbidity  Potability  
0       564.308654       10.379783        86.990970   2.963135           0  
1       592.885359       15.180013        56.329076   4.500656           0  
2       418.606213       16.868637        66.420093   3.055934           0  
3       363.266516       18.436525       100.341674   4.628771           0  
4       398.410813       11.558279        31.997993   4.075075           0  
...            ...             ...              ...        ...         ...  
3271    526.424171       13.894419        66.687695   4.435821           1  
3272    392.449580       19.903225              NaN   2.798243           1  
3273    432.044783       11.039070        69.845400   3.298875           1  
3274    402.883113       11.168946        77.488213   4.708658           1  
3275    327.459761       16.140368        78.698446   2.309149           1  

[3276 rows x 10 columns]

In [2]:
df.isna().sum()

ph                 491
Hardness             0
Solids               0
Chloramines          0
Sulfate            781
Conductivity         0
Organic_carbon       0
Trihalomethanes    162
Turbidity            0
Potability           0
dtype: int64

In [3]:
df.shape

(3276, 10)

In [4]:
df["ph"].mean()


np.float64(7.080794504263196)

In [5]:
df["Sulfate"].mean()

np.float64(333.775776610501)

In [6]:
df["Trihalomethanes"].mean()

np.float64(66.39629294665929)

In [7]:
df["ph"]=df["ph"].fillna(df["ph"]).mean()
df["Sulfate"]=df["Sulfate"].fillna(df["Sulfate"]).mean()
df["Trihalomethanes"]=df["Trihalomethanes"].fillna(df["Trihalomethanes"]).mean()

In [8]:
df.isna().sum()

ph                 0
Hardness           0
Solids             0
Chloramines        0
Sulfate            0
Conductivity       0
Organic_carbon     0
Trihalomethanes    0
Turbidity          0
Potability         0
dtype: int64

In [9]:
df.dtypes


ph                 float64
Hardness           float64
Solids             float64
Chloramines        float64
Sulfate            float64
Conductivity       float64
Organic_carbon     float64
Trihalomethanes    float64
Turbidity          float64
Potability           int64
dtype: object

In [10]:
x=df.iloc[:,:-1]
x

ph    Hardness       Solids  Chloramines     Sulfate  \
0     7.080795  204.890456  20791.31898     7.300212  333.775777   
1     7.080795  129.422921  18630.05786     6.635246  333.775777   
2     7.080795  224.236259  19909.54173     9.275884  333.775777   
3     7.080795  214.373394  22018.41744     8.059332  333.775777   
4     7.080795  181.101509  17978.98634     6.546600  333.775777   
...        ...         ...          ...          ...         ...   
3271  7.080795  193.681736  47580.99160     7.166639  333.775777   
3272  7.080795  193.553212  17329.80216     8.061362  333.775777   
3273  7.080795  175.762646  33155.57822     7.350233  333.775777   
3274  7.080795  230.603758  11983.86938     6.303357  333.775777   
3275  7.080795  195.102299  17404.17706     7.509306  333.775777   

      Conductivity  Organic_carbon  Trihalomethanes  Turbidity  
0       564.308654       10.379783        66.396293   2.963135  
1       592.885359       15.180013        66.396293   4.500656  
2       418.606213       16.868637        66.396293   3.055934  
3       363.266516       18.436525        66.396293   4.628771  
4       398.410813       11.558279        66.396293   4.075075  
...            ...             ...              ...        ...  
3271    526.424171       13.894419        66.396293   4.435821  
3272    392.449580       19.903225        66.396293   2.798243  
3273    432.044783       11.039070        66.396293   3.298875  
3274    402.883113       11.168946        66.396293   4.708658  
3275    327.459761       16.140368        66.396293   2.309149  

[3276 rows x 9 columns]

In [11]:
y=df.iloc[:,-1]
y

0       0
1       0
2       0
3       0
4       0
       ..
3271    1
3272    1
3273    1
3274    1
3275    1
Name: Potability, Length: 3276, dtype: int64

In [12]:
y.value_counts()

Potability
0    1998
1    1278
Name: count, dtype: int64

In [13]:
from imblearn.over_sampling import SMOTE
oversample=SMOTE(random_state=1)
x_os,y_os=oversample.fit_resample(x,y)

In [14]:
y_os.value_counts()

Potability
0    1998
1    1998
Name: count, dtype: int64

In [15]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x_os)
x_scaled

array([[-8.88178420e-16,  2.65520964e-01, -1.47306337e-01, ...,
        -1.21825408e+00, -1.42108547e-14, -1.32888472e+00],
       [-8.88178420e-16, -2.07763988e+00, -3.92806570e-01, ...,
         2.82090833e-01, -1.42108547e-14,  7.10106309e-01],
       [-8.88178420e-16,  8.66180972e-01, -2.47468468e-01, ...,
         8.09881819e-01, -1.42108547e-14, -1.20581970e+00],
       ...,
       [-8.88178420e-16,  8.77097109e-01,  7.16884488e-01, ...,
        -1.03785414e-02, -1.42108547e-14,  6.24800909e-01],
       [-8.88178420e-16, -3.09491640e-01,  1.56383792e+00, ...,
        -1.88578191e-01, -1.42108547e-14, -4.26108760e-01],
       [-8.88178420e-16, -4.54977580e-01, -3.89001010e-01, ...,
        -1.22552988e-01, -1.42108547e-14, -5.05387552e-01]])

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y_os,test_size=0.3,random_state=1)

In [17]:
x_train

array([[-8.88178420e-16, -1.39818012e+00,  1.92332444e-01, ...,
         8.14750549e-01, -1.42108547e-14,  4.05076624e-01],
       [-8.88178420e-16, -1.37289726e-01, -1.34803417e+00, ...,
        -6.35813907e-01, -1.42108547e-14, -1.07483885e+00],
       [-8.88178420e-16, -5.20340774e-01,  6.66040024e-01, ...,
        -1.38265800e-01, -1.42108547e-14, -4.43183816e-01],
       ...,
       [-8.88178420e-16,  1.81367045e-01, -4.47850739e-01, ...,
        -7.77453350e-01, -1.42108547e-14, -2.19367207e-01],
       [-8.88178420e-16,  2.75567842e-01, -5.04086503e-01, ...,
        -1.02458353e+00, -1.42108547e-14,  1.62541257e+00],
       [-8.88178420e-16, -4.40169336e-01,  9.72191264e-01, ...,
         1.35899076e-01, -1.42108547e-14, -1.45108922e-01]])

In [18]:
y_train

1848    0
3181    1
576     0
2728    1
1051    0
       ..
3839    1
1096    1
3980    1
235     0
1061    0
Name: Potability, Length: 2797, dtype: int64

In [19]:
x_test

array([[-8.88178420e-16,  1.05908806e+00, -6.54741352e-01, ...,
        -2.97397758e-01, -1.42108547e-14,  1.94080176e+00],
       [-8.88178420e-16,  3.75686296e+00,  2.73725670e-01, ...,
        -7.01724451e-01, -1.42108547e-14,  8.98503882e-01],
       [-8.88178420e-16,  2.60694211e-01,  1.33015048e+00, ...,
        -1.05414765e-01, -1.42108547e-14, -1.59226900e-01],
       ...,
       [-8.88178420e-16,  1.89998529e-01,  5.06984752e-01, ...,
         1.16292205e+00, -1.42108547e-14,  5.16327500e-01],
       [-8.88178420e-16,  2.49614861e+00, -5.59519759e-01, ...,
         7.88557803e-02, -1.42108547e-14, -6.82237601e-01],
       [-8.88178420e-16,  1.27459348e+00,  2.36503891e-01, ...,
         6.06190034e-01, -1.42108547e-14,  3.72747908e-01]])

In [20]:
y_test

200     0
2861    1
610     0
1918    1
3560    1
       ..
549     0
3255    1
1534    1
218     0
3748    1
Name: Potability, Length: 1199, dtype: int64

In [21]:
#algorithm
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
from sklearn.svm import SVC
sv=SVC()
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()

In [22]:
from sklearn.metrics import classification_report

In [23]:
lst=[knn,nb,lr,dt,sv,rf]
for i in lst:
  print("**********",i,"**********")
  i.fit(x_train,y_train)
  y_pred=i.predict(x_test)
  print(classification_report(y_test,y_pred))

********** KNeighborsClassifier() **********
              precision    recall  f1-score   support

           0       0.58      0.53      0.55       593
           1       0.58      0.63      0.60       606

    accuracy                           0.58      1199
   macro avg       0.58      0.58      0.58      1199
weighted avg       0.58      0.58      0.58      1199

********** GaussianNB() **********
              precision    recall  f1-score   support

           0       0.52      0.61      0.56       593
           1       0.54      0.44      0.48       606

    accuracy                           0.52      1199
   macro avg       0.53      0.53      0.52      1199
weighted avg       0.53      0.52      0.52      1199

********** LogisticRegression() **********
              precision    recall  f1-score   support

           0       0.51      0.56      0.53       593
           1       0.52      0.46      0.49       606

    accuracy                           0.51      1199
   ma